### ISSUE TITLE
input type="file" - upload() doesn't trigger onChange in React

### ISSUE THREAD

**Issue by ybentz** [testing-library/user-event#380]
- `@testing-library/user-event` version: 12.0.0+
- Testing Framework and version: jest@26.1.0
- DOM Environment: jsdom@16.2.2

Relevant code or config:

All relevant code is in the codesandbox, no special config needed.

What you did:

I have a project with a form that includes a `<input type="file"/>`. I wrote a test for the form that was working well up until I upgraded from v11 to v12. I created a simple codesandbox that reproduces the issue.
The repro includes a simple form with just the relevant input element and a form clear button because the value is read-only and I wanted to make sure the test is clean. The test calls `userEvent.upload` to upload a fake file and checks if the callback inside of `onChange` was called.

What happened:

In the small repro sandbox the test is passing on v11 (11.4.2 specifically, which is the latest) but fails on 12.0.0.

![image](https://user-images.githubusercontent.com/14811577/85600143-0d723600-b602-11ea-97d4-386ae66b6d60.png)

Reproduction repository:

https://codesandbox.io/s/testing-library-user-event-file-input-change-event-728w8

Problem description:

In React, `onChange` is not triggered when using `userEvent.upload(...)` to add a file to a `<input type="file"/>`.
When I came to file this issue I found [this similar issue](https://github.com/testing-library/user-event/issues/358) that already has a merged fix PR so I suspect the solution should be pretty straight forward requiring a similar for `upload` as was changed for `selectOptions`. Considering this is the second function that broke in the same way, it's probably worth it to check if there are more similar cases as well.

Suggested solution:

The solution should be very similar to [this merged PR](https://github.com/testing-library/user-event/pull/370). I can try to get a PR for it this evening but I figured I'd file the issue now in case someone else can get it done earlier.

**Comment by kentcdodds** [comment]
Pull request would be appreciated 👍👍

**Comment by ybentz** [comment]
@kentcdodds I have the fix + tests pretty much ready to go but when trying to commit any changes the pre-commit hook fails with this linter error:
![image](https://user-images.githubusercontent.com/14811577/85638136-f94a2b00-b639-11ea-817b-33c477a1a59a.png)

This is obviously not related to the PR itself and I see that this is the case all across the user-event library that imports from `/dom` directly. This is my first time contributing to this repo so I don't want to make any assumptions on what to do to fix/bypass it.

**Comment by kentcdodds** [comment]
The last line in the screenshot shows you how to bypass this.

I think if you update your branch to the latest on master then this should be fixed.

**Comment by ybentz** [comment]
Thanks for the quick reply!

> The last line in the screenshot shows you how to bypass this.

Cool, I figured that much but didn't know if that's the preferred way to go so I asked first.

>I think if you update your branch to the latest on master then this should be fixed.

I forked from the latest commit on master and looking at [the code](https://github.com/testing-library/user-event/blob/master/src/upload.js#L1), it's still importing from there so unless the fix happened somewhere else I don't think it's fixed yet.

**Comment by kentcdodds** [comment]
We should disable that rule in the package.json of this project. I can do that later, or if you'd like to do that before me that would be welcome as well.

**Comment by ybentz** [comment]
Sure. I'll submit a PR shortly.

**Comment by tmanundercover** [comment]
I am still having this issue.

**Comment by ph-fritsche** [comment]
@tmanundercover Could you please try to create a reproduction at codesandbox?
The issue as described above is solved. There is a test ensuring that we fire those `input` and `change` events.
https://github.com/testing-library/user-event/blob/673c2257ef63f69dd46b9fe2d4bbc3146db1426b/src/__tests__/upload.js#L4-L36
